# Generated by Django 4.0.3 on 2022-10-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Svaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('sposob', models.ImageField(upload_to='image/', verbose_name='Способ обратной связи')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('pravki', models.CharField(max_length=1000, verbose_name='Предложенные правки')),
                ('otvet', models.BooleanField(default=False, verbose_name='Ответили')),
            ],
            options={
                'verbose_name': 'Связь с администратором',
                'verbose_name_plural': 'Связь с администратором',
            },
        ),
    ]
